AllCops:
  TargetRubyVersion: 3.1.3
  TargetRailsVersion: 6.1.3
  Exclude:
    - "vendor/**/*"
    - "node_modules/**/*"
    - "db/migrate/**/*"
    - "bin/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - 'vendor/**/*'

Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
